tap "aws/tap"
tap "bazelbuild/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jenkins-x/jx"
tap "karhoo/brew", "git@github.com:karhoo/brew"
tap "karhoo/envy", "git@github.com:karhoo/envy"
tap "lhopki01/brew", "git@github.com:lhopki01/brew"
cask "adoptopenjdk8"
brew "ansible"
brew "aws-shell"
brew "awscli"
brew "binutils"
brew "consul"
brew "coreutils"
brew "diff-so-fancy"
brew "diffutils"
brew "docker", link: false
brew "docker-machine-parallels"
brew "ed"
brew "findutils"
brew "gawk"
brew "git"
brew "git-crypt"
brew "git-secrets"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnutls"
brew "go"
brew "grep"
brew "gzip"
brew "hashcat"
brew "hub"
brew "jq"
brew "lastpass-cli"
brew "less"
brew "m4"
brew "make"
brew "mas"
brew "minikube"
brew "nano"
brew "nmap"
brew "packer"
brew "pyenv-virtualenv"
brew "python"
brew "reattach-to-user-namespace"
brew "screen"
brew "stow"
brew "swagger-codegen"
brew "terraform"
brew "tmux"
brew "unrar"
brew "vault"
brew "watch"
brew "wdiff"
brew "wget"
brew "wpscan"
brew "yamllint"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "aws/tap/aws-sam-cli"
brew "bazelbuild/tap/bazel"
brew "jenkins-x/jx/jx"
brew "karhoo/envy/envy"
brew "karhoo/brew/k-tools"
brew "karhoo/brew/kubernetes-helm"
brew "lhopki01/brew/docker-chain-builder"
brew "lhopki01/brew/git-mass-sync"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alfred"
cask "anaconda"
cask "balenaetcher"
cask "brave-browser"
cask "canon-pixma-scanner-driver-ica"
cask "cyberduck"
cask "dash"
cask "discord"
cask "docker"
cask "docker-toolbox"
cask "duet"
cask "eddie"
cask "evernote"
cask "firefox"
cask "font-bitter"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-input"
cask "font-kreon"
cask "font-merriweather"
cask "font-merriweather-sans"
cask "font-pt-mono"
cask "font-pt-sans"
cask "font-pt-serif"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "iterm2"
cask "jabra-direct"
cask "keybase"
cask "lastpass"
cask "logitech-options"
cask "onionshare"
cask "pgadmin4"
cask "postman"
cask "protonmail-bridge"
cask "pycharm-ce"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "tor-browser"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "wireshark"
mas "1Blocker", id: 1107421413
mas "Comment Wrapper", id: 1377998565
mas "Evernote Web Clipper", id: 1481669779
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "Honey", id: 1472777122
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SketchBook", id: 863486266
mas "Xcode", id: 497799835
